packages/vendure-plugin-google-cloud-tasks/package.json, packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-job-queue.strategy.ts, packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.handler.ts, packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.plugin.ts, packages/vendure-plugin-google-cloud-tasks/src/types.ts
- Queues are created lazily to avoid startup race conditions
- Added `body-parser` to parse json bodies
=> Google Gloud Tasks Improvements

packages/vendure-plugin-google-storage-assets/src/google-storage-config.ts, packages/vendure-plugin-google-storage-assets/src/google-storage-strategy.ts
fixes https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/21
=> feat: allow to pass storage options to vendure-plugin-google-storage-assets

packages/vendure-plugin-goedgepickt/README.md, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.client.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.controller.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.resolver.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.types.ts, packages/vendure-plugin-goedgepickt/test/dev-server.ts, packages/vendure-plugin-goedgepickt/test/goedgepickt.spec.ts
Don't sync on startup anymore, it has to much load on the DB
=> feat(goedgepickt): sync via endpoint

.github/workflows/test.yaml, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.client.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.resolver.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts, packages/vendure-plugin-goedgepickt/test/goedgepickt.spec.ts
Sync in worker, to take load off of main thread
=> feat(goedgepickt): Sync in worker

packages/vendure-plugin-invoices/src/api/strategies/s3-storage.strategy.ts
=> Add signatureVersion to config

packages/vendure-plugin-webhook/README.md, packages/vendure-plugin-webhook/src/api/webhook-plugin-options.ts, packages/vendure-plugin-webhook/src/api/webhook.service.ts, packages/vendure-plugin-webhook/src/webhook.plugin.ts, packages/vendure-plugin-webhook/test/e2e.spec.ts
=> feat(webhook): pass injector to requestFn

packages/vendure-plugin-webhook/src/api/webhook.service.ts
Just a type change in the code
=> Typo Change

packages/vendure-plugin-customer-managed-groups/src/api-extensions.ts, packages/vendure-plugin-customer-managed-groups/src/customer-managed-groups.service.ts
These were the changes I meant to commit - not PR 109 - sorry about that!
=> Updated to allow myCustomerManagedGroup to work.

packages/vendure-plugin-customer-managed-groups/src/api-extensions.ts, packages/vendure-plugin-customer-managed-groups/src/customer-managed-groups.service.ts, packages/vendure-plugin-customer-managed-groups/test/customer-managed-groups.spec.ts, packages/vendure-plugin-customer-managed-groups/test/test-helpers.ts, packages/vendure-plugin-customer-managed-groups/yarn.lock
Implemented the update customer detail feature with test cases
=> fix: implemented updating group member details with test cases

.eslintrc.json, .github/workflows/test.yaml, CONTRIBUTING.md, README.md, package.json, packages/test/src/admin-utils.ts, packages/test/src/initial-data.ts, packages/test/src/shop-utils.ts
Linting `packages/test` for now, gradually add other packages.
* Pre-commit doesn't allow committing when `lint:check` fails
* Test action on PR fails when lint:check fails
=> Started linting: Only packages/test

packages/vendure-plugin-customer-managed-groups/src/api-extensions.ts, packages/vendure-plugin-customer-managed-groups/src/customer-managed-groups.service.ts, packages/vendure-plugin-customer-managed-groups/test/customer-managed-groups.spec.ts, packages/vendure-plugin-customer-managed-groups/test/test-helpers.ts, packages/vendure-plugin-customer-managed-groups/yarn.lock
This PR implements #131. 
Does this PR include any breaking changes we should be aware of? No
Add screenshots if needed. (Only if it makes this PR clearer)
=> Update Customer Custom Fields in UpdateCustomerManagedGroupMemberInput

packages/test/src/admin.graphql, packages/test/src/generated/admin-graphql.ts, packages/test/src/generated/shop-graphql.ts, packages/vendure-plugin-picqer/README.md, packages/vendure-plugin-picqer/package.json, packages/vendure-plugin-picqer/src/api/picqer.client.ts, packages/vendure-plugin-picqer/src/api/picqer.controller.ts, packages/vendure-plugin-picqer/src/api/picqer.service.ts, packages/vendure-plugin-picqer/src/api/types.ts, packages/vendure-plugin-picqer/src/picqer.plugin.ts, packages/vendure-plugin-picqer/test/dev-server.ts, packages/vendure-plugin-picqer/test/picqer.spec.ts
Creating webhooks in Picqer when Picqer config is created or updated, so that we can receive status updates.
Yes, `vendureHost` is needed when initializing the plugin.
=> Picqer: Update stock on incoming webhooks

packages/test/src/admin.graphql, packages/test/src/generated/admin-graphql.ts, packages/test/src/initial-data.ts, packages/util/src/order-state-util.ts, packages/vendure-plugin-picqer/README.md, packages/vendure-plugin-picqer/src/api/picqer.client.ts, packages/vendure-plugin-picqer/src/api/picqer.handler.ts, packages/vendure-plugin-picqer/src/api/picqer.service.ts, packages/vendure-plugin-picqer/src/api/types.ts, packages/vendure-plugin-picqer/src/picqer.plugin.ts, packages/vendure-plugin-picqer/test/dev-server.ts, packages/vendure-plugin-picqer/test/picqer.spec.ts, packages/vendure-plugin-picqer/test/test-helpers.ts, packages/vendure-plugin-webhook/src/api/webhook.resolver.ts, packages/vendure-plugin-webhook/test/dev-server.ts
1. Push orders to Picqer on order placement
2. Add custom Notes to orders in Picqer
3. Update order status in Vendure based on incoming webhooks from Picqer.
No
Flow:
Processing:
After picking in Picqer:
Result in Picqer:
Result in Vendure:
=> Picqer: Synchronize orders with Picqer

packages/vendure-plugin-stripe-subscription/README.md, packages/vendure-plugin-stripe-subscription/codegen.yml, packages/vendure-plugin-stripe-subscription/src/api/graphql-schemas.ts, packages/vendure-plugin-stripe-subscription/src/api/pricing.helper.ts, packages/vendure-plugin-stripe-subscription/src/api/schedule.entity.ts, packages/vendure-plugin-stripe-subscription/src/api/schedule.service.ts, packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.controller.ts, packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.service.ts, packages/vendure-plugin-stripe-subscription/src/api/subscription-order-item-calculation.ts, packages/vendure-plugin-stripe-subscription/src/stripe-subscription.plugin.ts, packages/vendure-plugin-stripe-subscription/src/ui/queries.ts, packages/vendure-plugin-stripe-subscription/src/ui/schedules.component.ts, packages/vendure-plugin-stripe-subscription/test/dev-server.ts, packages/vendure-plugin-stripe-subscription/test/helpers.ts, packages/vendure-plugin-stripe-subscription/test/stripe-subscription.spec.ts
Make the price and rate calculation tax aware depending on the channels tax setting.
This PR includes a breaking change.
Graphql schema will change a field from downpaymentWithTax to downpayment. These graphql fields are updated:
```diff
type StripeSubscriptionSchedule {
id: ID!
createdAt: DateTime
updatedAt: DateTime
name: String!
- downpaymentWithTax: Int!
+ downpayment: Int!
+ pricesIncludeTax: Boolean!
durationInterval: SubscriptionInterval!
durationCount: Int!
startMoment: SubscriptionStartMoment!
paidUpFront: Boolean!
billingInterval: SubscriptionInterval!
billingCount: Int!
fixedStartDate: DateTime
useProration: Boolean
autoRenew: Boolean
}
input UpsertStripeSubscriptionScheduleInput {
id: ID
name: String!
- downpaymentWithTax: Int!
+ downpayment: Int!
durationInterval: …
```
=> feat(stripe-subscription): make prices tax aware

.github/CODEOWNERS
Only allow merging of PR's by me!
=> feat: codeowners martijn

packages/vendure-plugin-picqer/test/picqer.spec.ts
=> feat(picqer): test

packages/vendure-plugin-metrics/src/api/metrics.service.ts
Fetch orders in batches with skip/take for improved performance
=> Feat(metrics): fetch orders in batches for perfromance

packages/vendure-plugin-goedgepickt/src/api/goedgepickt.controller.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.handler.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.resolver.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts, packages/vendure-plugin-myparcel/src/api/myparcel.service.ts
* Removed unneeded error logging from Goedgepickt
* Removed unneeded error logging from MyParcel
=> Fix/: Remove unneeded error logging

packages/test/src/admin-utils.ts, packages/test/src/generated/admin-graphql.ts, packages/vendure-order-client/src/graphql-types.ts, packages/vendure-order-client/src/queries.ts, packages/vendure-order-client/src/vendure-order-client.ts, packages/vendure-order-client/test/initial-data.ts, packages/vendure-order-client/test/queries.ts, packages/vendure-order-client/test/test-payment-method-handler.ts, packages/vendure-order-client/test/test-utils.ts, packages/vendure-order-client/test/vendure-order-client.spec.ts
All the methods required by the e2e tests under Guest Checkout have been implemented. closes https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/175
This PR doesn't include any breaking changes.
=> Guest checkout for Vendure Client

packages/vendure-order-client/package.json, packages/vendure-order-client/src/graphql-types.ts, packages/vendure-order-client/src/queries.ts, packages/vendure-order-client/test/dev-server.ts, packages/vendure-order-client/test/initial-data.ts, packages/vendure-order-client/yarn.lock, packages/vendure-plugin-stripe-subscription/package.json
* Upgraded dependencies 
* Added product slug, name and id to active order
* Added subtotal and total to active order fields
=> Feat(Vendure order client): Extra fields in active order

docs-website/.astro/types.d.ts, packages/vendure-plugin-modify-customer-orders/package.json, packages/vendure-plugin-modify-customer-orders/src/api/api.resolver.ts, packages/vendure-plugin-modify-customer-orders/src/api/order-transition-listener.service.ts, packages/vendure-plugin-modify-customer-orders/src/modify-customer-orders.plugin.ts, packages/vendure-plugin-modify-customer-orders/src/ui/convert-to-draft-button.module.ts, packages/vendure-plugin-modify-customer-orders/test/dev-server.ts, packages/vendure-plugin-modify-customer-orders/test/modify-customer-orders.spec.ts, packages/vendure-plugin-modify-customer-orders/test/tsconfig.e2e.json, packages/vendure-plugin-modify-customer-orders/tsconfig.json, packages/vendure-plugin-modify-customer-orders/vitest.config.js, packages/vendure-plugin-modify-customer-orders/yarn.lock
The plugin has been updated to `vendure 2.0.1` and we needed to add some typecasting to `any` to use util functions for testing from `test` package. Once `test` is updated to `vendure 2.0.1` this package will need to work without those.
This PR wont include any breaking changes. 
=> Update modify customer order plugin

packages/vendure-plugin-multiserver-db-sessioncache/src/session-cache.strategy.ts
* Log errors when saving or retrieving cached sessions, instead of propagating the errors: It's only caching, so errors should be logged, but not bother the client.
* Improved performance by using TypeORM's `upsert`:
```md
Unlike save method executes a primitive operation without cascades, relations and other operations included. Executes fast and efficient INSERT ... ON CONFLICT DO UPDATE/ON DUPLICATE KEY UPDATE query
```
=> fix(multiserver-db-sessioncache): performance and error loging

packages/vendure-plugin-admin-ui-helpers/package.json, packages/vendure-plugin-admin-ui-helpers/src/ui/cancel-order-button.module.ts, packages/vendure-plugin-admin-ui-helpers/src/ui/complete-order-button.module.ts, packages/vendure-plugin-admin-ui-helpers/src/ui/order-state.util.ts, packages/vendure-plugin-admin-ui-helpers/yarn.lock
Upgraded Admin UI helpers to v2.0.4 as mentioned in #200 
This PR won't introduce any breaking changes
=> Upgraded Admin UI Helpers to v2.0.4

.github/workflows/test.yaml, packages/vendure-plugin-metrics/package.json, packages/vendure-plugin-metrics/test/metrics.spec.ts, packages/vendure-plugin-metrics/yarn.lock
Jest dependency was removed from package.json, github workflow test enabled and import from `dist` in metrics.spec.ts was also updated to import from `src`.
This PR won't include any breaking changes.
=> Metrics Dependecy Fix

lerna.json, packages/test/package.json, packages/util/package.json, packages/vendure-order-client/package.json, packages/vendure-plugin-admin-ui-helpers/package.json, packages/vendure-plugin-coinbase/package.json, packages/vendure-plugin-customer-managed-groups/package.json, packages/vendure-plugin-dutch-postalcode/package.json, packages/vendure-plugin-e-boekhouden/package.json, packages/vendure-plugin-goedgepickt/package.json, packages/vendure-plugin-google-cloud-tasks/package.json, packages/vendure-plugin-google-storage-assets/package.json, packages/vendure-plugin-invoices/package.json, packages/vendure-plugin-limit-variant-per-order/package.json, packages/vendure-plugin-metrics/package.json, packages/vendure-plugin-modify-customer-orders/package.json, packages/vendure-plugin-multiserver-db-sessioncache/package.json, packages/vendure-plugin-myparcel/package.json, packages/vendure-plugin-order-export/package.json, packages/vendure-plugin-picqer/package.json, packages/vendure-plugin-popularity-scores/package.json, packages/vendure-plugin-sendcloud/package.json, packages/vendure-plugin-shipping-by-weight-and-country/package.json, packages/vendure-plugin-stock-monitoring/package.json, packages/vendure-plugin-stripe-subscription/package.json, packages/vendure-plugin-variant-bulk-update/package.json, packages/vendure-plugin-webhook/package.json
* Increased all versions to 1.0.0
=> Release v1.0.0 of all @pinelab/* plugins

packages/vendure-plugin-google-cloud-tasks/README.md, packages/vendure-plugin-google-cloud-tasks/package.json, packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-job-queue.strategy.ts, packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.handler.ts, packages/vendure-plugin-google-cloud-tasks/test/e2e.spec.ts
Clear jobs after 3 days with endpoint `cloud-tasks/clear-jobs/3`
`cloud-tasks/clear-settled-jobs` is now `cloud-tasks/clear-jobs/1`
=> fix(google-cloud-tasks): clear jobs after x days

packages/test/src/generated/admin-graphql.ts, packages/test/src/generated/shop-graphql.ts, packages/test/src/shop-utils.ts, packages/test/src/shop.graphql, packages/vendure-plugin-picqer/package.json, packages/vendure-plugin-picqer/src/api/picqer.service.ts, packages/vendure-plugin-picqer/test/picqer.spec.ts
Fix for sending invoice data if billing address is set. Do not use shipping address instead.
=> fix: send invoice data to picqer if billing address is set

packages/vendure-plugin-primary-collection/CHANGELOG.md, packages/vendure-plugin-primary-collection/package.json, packages/vendure-plugin-primary-collection/src/primary-collection-plugin.ts, packages/vendure-plugin-primary-collection/src/ui/shared.module.ts, packages/vendure-plugin-primary-collection/tsconfig.json
The changes in this PR ifx the issue related to primary collection plugin admin ui extension.
Does this PR include any breaking changes we should be aware of? **No**
=> Primary Collection Plugin Fix

packages/vendure-order-client/CHANGELOG.md, packages/vendure-order-client/test/vendure-order-client.spec.ts
Forgot to push small typo's. No package release necessary
=> Eligible shipping methods store: forgot to push typo's

packages/vendure-order-client/CHANGELOG.md, packages/vendure-order-client/README.md, packages/vendure-order-client/package.json, packages/vendure-order-client/src/index.ts, packages/vendure-order-client/src/vendure-order-client.ts
The changes in this PR update outdated `vendure-order-client` readme and export `vendure` graphql types from the package to be used in storefronts.
=> Vendure Order Client Fixes

packages/test/src/shop-utils.ts, packages/vendure-plugin-picqer/src/api/picqer.service.ts, packages/vendure-plugin-picqer/test/dev-server.ts
Forgot to push, no need to directly publish this
=> feat(picqer): typos

packages/vendure-order-client/CHANGELOG.md, packages/vendure-order-client/package.json, packages/vendure-order-client/src/graphql-generated-types.ts, packages/vendure-order-client/src/queries.ts, packages/vendure-order-client/src/vendure-order-client.ts, packages/vendure-order-client/test/dev-server.ts, packages/vendure-order-client/test/vendure-order-client.spec.ts
Added `getMolliePaymentMethods` query
=> Order client: mollie payment methods

packages/vendure-plugin-admin-social-auth/src/api/login-controller.ts, packages/vendure-plugin-admin-social-auth/src/ui/login.html
The changes in this PR update LocalStorage only if the `authOptions.tokenMethod` is `cookie`.
📌 Always:
=> Update LocalStorage only if the tokenMethod is cookies

packages/vendure-plugin-modify-customer-orders/CHANGELOG.md, packages/vendure-plugin-modify-customer-orders/package.json, packages/vendure-plugin-modify-customer-orders/src/api/api.resolver.ts, packages/vendure-plugin-modify-customer-orders/src/custom-order-process.ts, packages/vendure-plugin-modify-customer-orders/src/modify-customer-orders.plugin.ts, packages/vendure-plugin-modify-customer-orders/src/ui/order-state.util.ts
The changes in this PR fixes and closes #342 
📌 Always:
=> Convert Draft to Order Fixes

packages/vendure-plugin-picqer/CHANGELOG.md, packages/vendure-plugin-picqer/package.json, packages/vendure-plugin-picqer/src/picqer.plugin.ts
I'd like to push the field fixedstockprice to Picqer but the Picqer Plugin doesn't allow this from a type perspective. Therefore adding support for that.
=> feat: support pushing and pulling of Picqer product data

packages/vendure-plugin-invoices/CHANGELOG.md, packages/vendure-plugin-invoices/README.md, packages/vendure-plugin-invoices/package.json, packages/vendure-plugin-invoices/src/index.ts, packages/vendure-plugin-invoices/src/strategies/load-data-fn.ts, packages/vendure-plugin-invoices/src/util/default-template.ts, packages/vendure-plugin-invoices/src/util/v2-migration.ts
- Added script for migrating to V2
- Updated default template to support credit invoices
📌 Always:
=> Feat: Invoices migration script and credit invoices template

packages/vendure-plugin-modify-customer-orders/CHANGELOG.md, packages/vendure-plugin-modify-customer-orders/package.json, packages/vendure-plugin-modify-customer-orders/src/api/api.resolver.ts, packages/vendure-plugin-modify-customer-orders/src/api/modify-customer-order.service.ts, packages/vendure-plugin-modify-customer-orders/src/modify-customer-orders.plugin.ts
The changes in this PR implement and close #343 
📌 Always:
=> Extract modify-custom-orders-service to service class

packages/vendure-plugin-shipping-extensions/CHANGELOG.md, packages/vendure-plugin-shipping-extensions/README.md, packages/vendure-plugin-shipping-extensions/package.json, packages/vendure-plugin-shipping-extensions/src/shipping-extensions.plugin.ts, packages/vendure-plugin-shipping-extensions/src/weight-and-country-checker.ts
Allow a custom weightCalculationFunction
📌 Always:
=> feat(shipping-extensions): custom weight calculation function - v2.1.0

packages/vendure-plugin-shipping-extensions/CHANGELOG.md, packages/vendure-plugin-shipping-extensions/package.json, packages/vendure-plugin-shipping-extensions/src/distance-based-shipping-calculator.ts, packages/vendure-plugin-shipping-extensions/test/shipping-extensions.spec.ts
Allow setting a fallback price for distance based calculator
📌 Always:
=> feat(shipping-extensions): allow a fallback price

packages/vendure-plugin-invoices/CHANGELOG.md, packages/vendure-plugin-invoices/package.json, packages/vendure-plugin-invoices/src/api/invoice.controller.ts, packages/vendure-plugin-invoices/src/services/invoice.service.ts, packages/vendure-plugin-invoices/src/ui/invoices.component.scss, packages/vendure-plugin-invoices/src/ui/invoices.component.ts, packages/vendure-plugin-invoices/test/dev-server.ts
The changes in this PR implement and close #352 
📌 Always:
=> Invoice UI Improvements

packages/vendure-plugin-picqer/CHANGELOG.md, packages/vendure-plugin-picqer/package.json
See https://github.com/Pinelab-studio/pinelab-vendure-plugins/pull/383
=> feat(picqer): Unlimited stock - changelog and version

packages/vendure-plugin-shipping-extensions/CHANGELOG.md, packages/vendure-plugin-shipping-extensions/package.json, packages/vendure-plugin-shipping-extensions/src/config/weight-and-country-checker.ts
The changes in this PR fix and close #417 
📌 Always:
=> Fix Order discount getting removed issue

packages/vendure-plugin-invoices/CHANGELOG.md, packages/vendure-plugin-invoices/package.json, packages/vendure-plugin-invoices/src/services/invoice.service.ts
Closes https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/433
No
📌 Always:
=> feat(invoices): Prevent concurrency issues

packages/vendure-plugin-sendcloud/CHANGELOG.md, packages/vendure-plugin-sendcloud/package.json, packages/vendure-plugin-sendcloud/src/api/sendcloud.controller.ts, packages/vendure-plugin-sendcloud/test/dev-server.ts
Added better logging for failing incoming webhooks
📌 Always:
=> Fix/sendcloud webhook V1.2.2

packages/vendure-plugin-popularity-scores/CHANGELOG.md, packages/vendure-plugin-popularity-scores/package.json, packages/vendure-plugin-popularity-scores/src/popularity-scores.service.ts, packages/vendure-plugin-popularity-scores/test/dev-server.ts, packages/vendure-plugin-popularity-scores/test/e2e.spec.ts, packages/vendure-plugin-popularity-scores/test/helpers.ts, packages/vendure-plugin-popularity-scores/test/queries.ts
The changes in this PR implement and fix #423 
📌 Always:
=> Fix Score Calculation Issue for Parent Collections

.husky/pre-commit, eslint-base.config.js, packages/vendure-plugin-klaviyo/CHANGELOG.md, packages/vendure-plugin-klaviyo/README.md, packages/vendure-plugin-klaviyo/package.json, packages/vendure-plugin-klaviyo/src/klaviyo.service.ts, packages/vendure-plugin-klaviyo/test/e2e.spec.ts, packages/vendure-plugin-klaviyo/test/mock-order-placed-handler.ts
Added extra tests for 'Ordered Prouct' events
:x: 
📌 Always:
=> feat(klaviyo): added more e2e tests

docs-website/src/api/contributors.ts, docs-website/src/components/Contributor.astro, docs-website/src/pages/index.astro
list of contributors now can be seen at the bottom the page
closes #445
=> feat(docs-website): added contributors to the website

packages/vendure-plugin-invoices/CHANGELOG.md, packages/vendure-plugin-invoices/package.json, packages/vendure-plugin-invoices/src/services/invoice.service.ts
Fetch order.customer relation by default
📌 Always:
=> feat(invoices): default customer relation patch

packages/vendure-scripts/CHANGELOG.md, packages/vendure-scripts/README.md, packages/vendure-scripts/package.json, packages/vendure-scripts/src/copy-database.ts, packages/vendure-scripts/src/index.ts
Added script for copying Production database to a Test database with mysqldump
📌 Always:
=> feat(vendure-scripts): Copy database script

packages/vendure-plugin-popularity-scores/CHANGELOG.md, packages/vendure-plugin-popularity-scores/package.json, packages/vendure-plugin-popularity-scores/src/popularity-scores.service.ts, packages/vendure-plugin-popularity-scores/test/dev-server.ts
Closes https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/478 
📌 Always:
=> feat(popularity-scores): Fixed dissapearing parent relations

packages/vendure-plugin-shipping-extensions/CHANGELOG.md, packages/vendure-plugin-shipping-extensions/README.md, packages/vendure-plugin-shipping-extensions/eslint.config.js, packages/vendure-plugin-shipping-extensions/package.json, packages/vendure-plugin-shipping-extensions/src/config/distance-based-shipping-calculator.ts, packages/vendure-plugin-shipping-extensions/src/config/order-in-country-promotion-condition.ts, packages/vendure-plugin-shipping-extensions/src/config/weight-and-country-checker.ts, packages/vendure-plugin-shipping-extensions/src/config/zone-aware-flat-rate-shipping-calculator.ts, packages/vendure-plugin-shipping-extensions/src/index.ts, packages/vendure-plugin-shipping-extensions/src/services/zone-aware-shipping-tax-calculation.service.ts, packages/vendure-plugin-shipping-extensions/src/shipping-extensions.plugin.ts, packages/vendure-plugin-shipping-extensions/src/strategies/order-address-to-geolocation-strategy.ts, packages/vendure-plugin-shipping-extensions/src/strategies/uk-postalcode-to-geolocation-strategy.ts, packages/vendure-plugin-shipping-extensions/src/ui/providers.ts, packages/vendure-plugin-shipping-extensions/src/ui/select-tax-category.component.ts, packages/vendure-plugin-shipping-extensions/test/dev-server.ts, packages/vendure-plugin-shipping-extensions/test/shipping-extensions.spec.ts, packages/vendure-plugin-shipping-extensions/test/test-helpers.ts, packages/vendure-plugin-shipping-extensions/tsconfig.eslint.json
The changes in this PR implement zone aware shipping calculator. 
📌 Always:
=> zone aware shipping calculator

packages/vendure-plugin-shipmate/CHANGELOG.md, packages/vendure-plugin-shipmate/package.json, packages/vendure-plugin-shipmate/src/api/shipmate.service.ts, packages/vendure-plugin-shipmate/src/api/util.ts
The changes in this PR implement and close #472 . It will also throw the any shipmate error it might run into so that the job will be  cancelled.
📌 Always:
=> Truncate shipmate payload strings

packages/vendure-plugin-picqer/CHANGELOG.md, packages/vendure-plugin-picqer/package.json, packages/vendure-plugin-picqer/src/api/picqer.service.ts, packages/vendure-plugin-picqer/test/picqer.spec.ts, yarn.lock
The changes in this PR implement and close #504 
📌 Always:
=> Transition to shipped

packages/vendure-plugin-metrics/CHANGELOG.md, packages/vendure-plugin-metrics/package.json, packages/vendure-plugin-metrics/src/ui/chartist/chartist.component.ts
Fixes for typescript build issues that I encountered trying to use the plugin; no functional changes.
This needs to happen to deploy this feature, for example:
None
N/A
📌 Always:
N/A
=> fix(metrics): Fix typescript build issues (fixes #525)

packages/vendure-plugin-metrics/CHANGELOG.md, packages/vendure-plugin-metrics/package.json, packages/vendure-plugin-metrics/src/api/metric-strategy.ts, packages/vendure-plugin-metrics/src/api/metrics.service.ts, packages/vendure-plugin-metrics/src/api/metrics/average-order-value.ts, packages/vendure-plugin-metrics/src/api/metrics/conversion.ts, packages/vendure-plugin-metrics/src/api/metrics/revenue-per-product.ts, packages/vendure-plugin-metrics/src/api/metrics/units-sold-metric.ts, packages/vendure-plugin-metrics/src/api/schema.graphql.ts, packages/vendure-plugin-metrics/src/index.ts, packages/vendure-plugin-metrics/src/metrics.plugin.ts, packages/vendure-plugin-metrics/src/ui/metrics-widget.shared-module.ts, packages/vendure-plugin-metrics/src/ui/metrics-widget.ts, packages/vendure-plugin-metrics/src/ui/queries.graphql.ts, packages/vendure-plugin-metrics/test/dev-server.ts, packages/vendure-plugin-metrics/test/metrics.spec.ts
- Allow specifying per metric if it's filterable by variant ID's
- Added conversion metric
- Fixed widget ID to prevent conflicts with Vendure's built in widget
📌 Always:
=> Feat/Metrics: Conversion metric

.github/CODEOWNERS
Allow Marc and Matthew to approve eachothers PR's
📌 Always:
=> feat: codeowners for accept blue

packages/vendure-plugin-admin-ui-helpers/CHANGELOG.md, packages/vendure-plugin-admin-ui-helpers/package.json, packages/vendure-plugin-admin-ui-helpers/src/ui/cancel-order-button.module.ts, packages/vendure-plugin-admin-ui-helpers/src/ui/complete-order-button.module.ts, packages/vendure-plugin-admin-ui-helpers/src/ui/order-state.util.ts
The changes in this PR implement and close #471
Nothing
Nothing
📌 Always:
=> Disable buttons on ArrangingPayment

packages/vendure-plugin-accept-blue/CHANGELOG.md, packages/vendure-plugin-accept-blue/package.json, packages/vendure-plugin-accept-blue/src/api/accept-blue-transaction-event.ts
Example: This PR implements feature X and closes #123
Example: Graphql field X was removed
📌 Always:
=> fix(accept-blue): correct ctx not being public

packages/vendure-plugin-klaviyo/CHANGELOG.md, packages/vendure-plugin-klaviyo/README.md, packages/vendure-plugin-klaviyo/package.json, packages/vendure-plugin-klaviyo/src/api/api-extensions.ts, packages/vendure-plugin-klaviyo/src/api/klaviyo-shop-resolver.ts, packages/vendure-plugin-klaviyo/src/service/klaviyo.service.ts, packages/vendure-plugin-klaviyo/test/dev-server.ts, packages/vendure-plugin-klaviyo/test/e2e.spec.ts
- Added mutation to sign up to Klaviyo Audience list
📌 Always:
=> feat(klaviyo): added newsletter signup mutation

packages/vendure-plugin-customer-managed-groups/CHANGELOG.md, packages/vendure-plugin-customer-managed-groups/package.json, packages/vendure-plugin-customer-managed-groups/src/api/customer-managed-groups.service.ts, packages/vendure-plugin-customer-managed-groups/test/customer-managed-groups.spec.ts
- Don't allow removing yourself from group
📌 Always:
=> feat(customer-managed-groups): cannot remove self from group

docs-website/src/components/HeroSection.astro, packages/vendure-plugin-stripe-subscription/CHANGELOG.md, packages/vendure-plugin-stripe-subscription/package.json, packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.service.ts, packages/vendure-plugin-stripe-subscription/test/dev-server.ts, yarn.lock
- Updated Stripe package to v17.7.0
Closes https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/571
📌 Always:
=> feat(stripe-subscription): update to client 17.7.0

packages/vendure-plugin-goedgepickt/CHANGELOG.md, packages/vendure-plugin-goedgepickt/package.json, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.handler.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.resolver.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts, packages/vendure-plugin-goedgepickt/src/custom-fields.ts, packages/vendure-plugin-goedgepickt/test/dev-server.ts, packages/vendure-plugin-goedgepickt/test/goedgepickt.spec.ts
- Setting allocated to 0 on incoming stock updates and full sync
📌 Always:
=> Goedgepickt: stock fix and test fixes

packages/vendure-scripts/CHANGELOG.md, packages/vendure-scripts/package.json, packages/vendure-scripts/src/index.ts, packages/vendure-scripts/src/populate-eu-zones-and-tax-rates.ts, packages/vendure-scripts/test/dev-server.ts
Added script to populate tax rates and zones
📌 Always:
=> feat(vendure-scripts): tax script

packages/vendure-plugin-goedgepickt/CHANGELOG.md, packages/vendure-plugin-goedgepickt/package.json, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.controller.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.resolver.ts, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts, packages/vendure-plugin-goedgepickt/test/dev-server.ts, packages/vendure-plugin-goedgepickt/test/goedgepickt.spec.ts
- Process incoming stock and order webhooks via the job queue, to prevent webhook disabling in GoedGepickt
📌 Always:
=> GoedGepickt: jobqueue for webhooks

.github/workflows/publish.yaml, .github/workflows/test.yaml
* Make Github actions test less brittle and faster
📌 Always:
=> Optimize Github Action Test.yaml

packages/vendure-plugin-accept-blue/CHANGELOG.md, packages/vendure-plugin-accept-blue/package.json, packages/vendure-plugin-accept-blue/src/api/accept-blue-client.ts, packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts, packages/vendure-plugin-accept-blue/test/dev-server.ts
- Correctly encode email addresses when looking up customers in Accept Blue. This prevents incorrect `Customer not found` errors when using email addresses with `+` in them.
- Fixed typo in error message
📌 Always:
=> fix(accept-blue): encode email addresses

packages/vendure-plugin-klaviyo/CHANGELOG.md, packages/vendure-plugin-klaviyo/README.md, packages/vendure-plugin-klaviyo/package.json, packages/vendure-plugin-klaviyo/src/event-handler/refund-event-handler.ts, packages/vendure-plugin-klaviyo/src/index.ts, packages/vendure-plugin-klaviyo/test/dev-server.ts, packages/vendure-plugin-klaviyo/test/e2e.spec.ts
- Added `RefundEventHandler` to send events to Klaviyo when a refund is created.
📌 Always:
=> feat(klaviyo): refund event

packages/vendure-plugin-goedgepickt/CHANGELOG.md, packages/vendure-plugin-goedgepickt/package.json, packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts, packages/vendure-plugin-google-cloud-tasks/CHANGELOG.md, packages/vendure-plugin-google-cloud-tasks/package.json, packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-service.ts
- Improved error logging when incoming webhooks fail
- Don't try to transition to Delivered when the order is in PaymentAuthorized state
- Add stack trace to error message when job fails
📌 Always:
=> Better error handling for Goedgepickt and Google Cloud Tasks
