packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.plugin.ts
packages/vendure-plugin-google-cloud-tasks/src/types.ts

This PR adds a config option to the google cloud tasks plugin. The config option controls the body size for the JSON body parser. I'm quite sure that cloud tasks can handle larger payloads than the default size limit setting.

Added a json body parser size limit as a config option

---

packages/vendure-plugin-google-cloud-tasks/package.json
packages/vendure-plugin-google-cloud-tasks/yarn.lock

I ran into the following issue, and it looks like an update to the google cloud tasks library resovles it:
https://github.com/googleapis/nodejs-tasks/issues/580
Also discussed first here:
https://github.com/googleapis/nodejs-tasks/issues/397

Bump google cloud tasks to v2.5.0

---

packages/vendure-plugin-invoices/src/api/strategies/google-storage-invoice-strategy.ts
packages/vendure-plugin-invoices/src/api/strategies/local-file-strategy.ts
packages/vendure-plugin-invoices/src/api/strategies/storage-strategy.ts
packages/vendure-plugin-invoices/src/invoice.plugin.ts
packages/vendure-plugin-invoices/test/e2e.spec.ts
packages/vendure-plugin-invoices/tsconfig.json

I added deferred library loading as implemented in asset storage strategy of vendure's [asset-server-plugin](https://github.com/vendure-ecommerce/vendure/blob/c6cf4d4e214f3941bc5f27017b0354dda732f9e0/packages/asset-server-plugin/src/s3-asset-storage-strategy.ts#L151) this removes the required dependency to @google-cloud/storage when using local storage or implement your own storage provider.

Deferred loading of libraries

---

packages/vendure-plugin-e-boekhouden/src/api/e-boekhouden.adapter.ts
packages/vendure-plugin-e-boekhouden/src/index.ts

Exporting the `recalculateTaxFromTotalIncVAT()`from e-boekhouden plugin so it can be reused in the consuming project.
Vendure calculates taxes per orderline, while the EBoekhouden plugin sends taxes per taxRate (from the ordersummary) to the EBoekhouden platform. This sometimes results in small rounding differences where `taxBase + taxTotal` is not equal to `taxBase * taxRate`.
The function calculates the totalIncVAT as `totalIncVAT = taxBase + taxTotal`, and recalculates the `totalExVAT` and the `totalTax` based on the new totalIncVAT.
By exporting this function we can reuse it in our InvoicePlugin template, so that there are no differences between invoices and tax administration

feat(e-boekhouden): exporting tax utility

---

packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.handler.ts
packages/vendure-plugin-invoices/src/api/invoice.service.ts

Return status 200 after max retries to prevent any more retries by Google Cloud Tasks. Removed final attempt logging in invoices plugin: should be handled by cloud tasks plugin

Fix: Google cloud tasks + invoices

---

packages/vendure-plugin-invoices/src/api/strategies/google-storage-invoice-strategy.ts
packages/vendure-plugin-invoices/src/api/strategies/local-file-strategy.ts
packages/vendure-plugin-invoices/src/api/strategies/s3-storage.strategy.ts

Suggesting simpler naming inside bucket and setting the content type for direct display from s3 url

invoice-plugin - s3 storage naming and content type

---

packages/vendure-plugin-shipping-by-weight-and-country/src/shipping-by-weight-and-country.plugin.ts
packages/vendure-plugin-shipping-by-weight-and-country/src/weight-and-country-checker.ts
packages/vendure-plugin-shipping-by-weight-and-country/test/shipping-by-weight-and-country.spec.ts

This change allows users to change weight of a product on a variant basis. If no variant weight is specified, the product weight is used. If this still doesn't exist then 0 is used (like before).
This probably doesn't need its own release, as I am intending to add more physical property features in the near future.

feat(shipping): variant weight overrides

---

packages/vendure-plugin-picqer/src/api/picqer.client.ts
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

* Append configured api endpoint with `/api/v1`, so the user doesn't have to specify that
* Use channel.defaultLanguage for sync instead of user context

feat(picqer): api url update and channel default

---

packages/vendure-plugin-google-cloud-tasks/README.md
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-job-queue.strategy.ts
packages/vendure-plugin-google-cloud-tasks/src/types.ts
packages/vendure-plugin-google-cloud-tasks/test/e2e.spec.ts

When a task is pushed into a Google cloud instance, sometime an ECONNRESET is returned from server. This change does a   configurable number of retries if that happens. Developers could pass an optional `createTaskRetries` field to `CloudTaskOptions`, otherwise the default is five times.
Breaking changes
Does this PR include any breaking changes we should be aware of? No
Add screenshots if needed. (Only if it makes this PR clearer)

Google Cloud plugin Retry on ECONNRESET

---

packages/vendure-plugin-stripe-subscription/src/api/pricing.helper.ts
packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.service.ts
packages/vendure-plugin-stripe-subscription/src/api/subscription.promotion.ts

Some discounts returned `-100`, while others returned `100`. All discounts should return the discount as a negative number (same way Vendure does it).
Closes #152 

feat(stripe-subscription): fixed negative discount calculation

---

.husky/pre-commit
packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.service.ts

* Fixed pre-subscription creation validations in Stripe Subscription plugin
* Use `lint:fix` instead of `lint:check` on pre-commit hook

Fix: Stripe Subscription validations and pre-commit lint:fix instead of check

---

packages/vendure-plugin-picqer/README.md
packages/vendure-plugin-picqer/src/api/picqer.client.ts
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/picqer.plugin.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

* Added a strategy function to allow pushing custom order fields to Picqer
* Refactored adding order notes to adding a single `customer_remark` field. (Order not is meant for employees)
`addPicqerOrderNote` was removed, because order notes can now be added as customer_remark
```diff
PicqerPlugin.init({
enabled: true,
vendureHost: 'https://example-vendure.io',
// Dummy data for testing purposes
pushProductVariantFields: (variant) => ({ barcode: variant.sku }),
pullPicqerProductFields: (picqerProd) => ({
outOfStockThreshold: 123,
}),
-        addPicqerOrderNote: (order) => 'test note',
+       pushPicqerOrderFields: (order) => ({
+         customer_remarks: 'test note',
+       }),
}),
```

feat(picqer): added order custom fields

---

packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/test/dev-server.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

* Register webhooks in Picqer for all channels that have Picqer enabled
* Push countryCode to Picqer instead of country name
* Push City to Picqer

fix(picqer): added webhook creation on startup and country and city push

---

.github/workflows/test.yaml
packages/vendure-plugin-variant-bulk-update/package.json
packages/vendure-plugin-variant-bulk-update/test/variant-bulk-update.spec.ts
packages/vendure-plugin-variant-bulk-update/tsconfig.json
packages/vendure-plugin-variant-bulk-update/vitest.config.js
packages/vendure-plugin-variant-bulk-update/yarn.lock

The changes should make [Vendure Variant Bulk Upload Plugin](https://github.com/Pinelab-studio/pinelab-vendure-plugins/tree/master/packages/vendure-plugin-variant-bulk-update) compatible with vendure 2.0. Should close https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/226
This PR won't include any breaking changes.

Upgraded Vendure Variant Bulk Update plugin to vendure 2.0

---

packages/vendure-plugin-invoices/CHANGELOG.md
packages/vendure-plugin-invoices/README.md
packages/vendure-plugin-invoices/package.json
packages/vendure-plugin-invoices/src/api/entities/invoice-config.entity.ts
packages/vendure-plugin-invoices/src/invoice.plugin.ts

By default, the plugin uses TypeOrm's `text` to store the invoice template in the DB. This might not be enough, for example when you'd like to add base64 encoded images to your invoices. This will result in the error `ER_DATA_TOO_LONG: Data too long for column 'templateString'`. You can specify your DB engine with an env variable, and the plugin will resolve the correct column type:
```shell
INVOICES_PLUGIN_DB_ENGINE=longtext
```
Don't forget to run a DB migration after! Checkout https://orkhan.gitbook.io/typeorm/docs/entities for available databases and column types.

Feat(invoices): Increase length of invoice template field in DB

---

packages/vendure-plugin-stripe-subscription/package.json
packages/vendure-plugin-stripe-subscription/src/ui/schedule-relation-selector.component.ts

The stripe subscriptions selector in product variant detail page now works.
This PR won't introduce any breaking changes.
- [] I have added or updated test cases for important functionality
- [] I have updated the README if needed

Stripe Subscription Selector Fix

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts

Check if customer firstname + lastname is the same as the given invoice or billing contactname. If they are the same, don't set a separate contact name in Picqer.
:arrow_up: This is what we prevent with this PR

fix(picqer): dont set contactname if its the same as customer name

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/api/types.ts

* Picqer uses a customers email when a registered customer is added to a picqer order. However, for guest orders no customer is connected, so no emailaddress is known to picqer. 
* This PR makes sure emailaddress and telephone numer are added to the order object, not just a customer

Fix: Picqer email for guests

---

packages/test/src/shop-utils.ts
packages/util/src/order-state-util.ts
packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.controller.ts
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/api/types.ts
packages/vendure-plugin-picqer/test/dev-server.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

Right now we handle order statusses in Vendure based on the `picklist.closed` webhook, but this doesnt always work: Sometimes, products are added/removed in Picqer, and the Vendure order isn't updated.
To not overcomplicate things, we will move Vendure orders based on the `orders.status_changed` webhook.
1. Vendure orders are Fulfilled right after they are placed and sent to Picqer
2. `completed` will move the order to Shipped and then to Delivered in Vendure
3.  `cancelled` will move the order to the Cancelled state.
Old `picklists.closed` webhooks need to be manually disabled in Picqer.

fix(picqer): Complete on `orders.status_changed` webhook

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

* Improved logging, so that when a push to Picqer job fails, we can find it by order code
* Always create products as active in Picqer. Disabled in Picqer has a different meaning than disabled in Vendure

fix(picqer): alwasy push active products and improved logging

---

packages/vendure-order-client/CHANGELOG.md
packages/vendure-order-client/package.json
packages/vendure-order-client/src/index.ts
packages/vendure-order-client/src/vendure-order-client.ts

The changes in this PR export the store helpers (`setResult`  and `HandleLoadingState`) and also makes `VendureOrderClient.updateEligibleShippingMethods` method public.

Vendure order client updates

---

packages/test/src/admin.graphql
packages/test/src/generated/admin-graphql.ts
packages/test/src/generated/shop-graphql.ts
packages/test/src/shop.graphql
packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/api/types.ts
packages/vendure-plugin-picqer/test/dev-server.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

* Cancel any order lines that don't exist in the Picqer order. This can happen when items have been manually removed in Picqer.
* Price is adjusted acordingly, but no refund is being done
* We don't add items in Vendure, because that would require additional payment.
We do this, because order lines can be removed in Picqer, after which an order is completed/closed in Picqer, but unable to fulfill in Vendure, because that item still exists (and can be a backorder without stock, so unfullfillable).

Feat(Picqer): Remove orderlines when removed in Picqer

---

packages/vendure-plugin-google-cloud-tasks/CHANGELOG.md
packages/vendure-plugin-google-cloud-tasks/package.json
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-job-queue.strategy.ts
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.plugin.ts
packages/vendure-plugin-google-cloud-tasks/src/types.ts
packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-stock-monitoring/CHANGELOG.md
packages/vendure-plugin-stock-monitoring/package.json
packages/vendure-plugin-stock-monitoring/src/ui/stock-widget.ts

* Cloud tasks: Only log errors when a job couldn't be added to the queue after its retries
* Cloud tasks: Implemented exponential backoff, so that there is a delay after which when a job will be retried
* Picqer: Log order code when a job failed to add to push-order queue, so that we can easily find which order its about

Picqer & Cloud Tasks plugin: Only log errors after retries exceeded

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts

* Use allocated + freestock for stock on hand in Vendure, because free stock in Vendure will be `stockOnHand - allocated`

patch(picqer): allocated + freestock as stockOnHand

---

packages/test/src/admin.graphql
packages/test/src/generated/admin-graphql.ts
packages/test/src/generated/shop-graphql.ts
packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/README.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.controller.ts
packages/vendure-plugin-picqer/src/api/picqer.resolvers.ts
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/picqer.plugin.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

* Expose endpoint to periodically pull stock levels: `/picqer/stock-sync`
* Custom order process:
* This plugin installs the default order process with `checkFulfillmentStates: false`, so that orders can be transitioned to Shipped and Delivered without the need of fulfilment. Fulfilment is the responsibility of Picqer, so we wont handle that in Vendure when using this plugin.
* The custom order process, together with a frequent full stock-sync, should make sure that:
* Vendure stock is always up-to-date
* Orders are always fulfillable after placement

Picqer: Expose stock level sync function

---

packages/vendure-plugin-google-cloud-tasks/CHANGELOG.md
packages/vendure-plugin-google-cloud-tasks/README.md
packages/vendure-plugin-google-cloud-tasks/package.json
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-job-queue.strategy.ts
packages/vendure-plugin-google-cloud-tasks/src/types.ts
packages/vendure-plugin-google-cloud-tasks/test/dev-server.ts
packages/vendure-plugin-google-cloud-tasks/test/e2e.spec.ts

- Allow setting `fallback:true` to fallback to HTTP instead of gRPC to prevent DEADLINE_EXCEEDED errors. For more details see https://github.com/googleapis/nodejs-tasks/issues/397#issuecomment-618580649
- Allow setting of all Google Cloud Tasks Client options via `clientOptions: ...`
- Removed `bodySizeLimit` option, because body-parser is loaded by NestJs since Vendure V2
Removed `bodySizeLimit` option, because body-parser is loaded by NestJs since Vendure V2
📌 Always:

feat(google-cloud-tasks): fallback option

---

packages/vendure-plugin-popularity-scores/CHANGELOG.md
packages/vendure-plugin-popularity-scores/package.json
packages/vendure-plugin-popularity-scores/src/popularity-scores.plugin.ts

The Changes in this PR allows us to set popularity scores manually.
📌 Always:

Popularity scores can now be set manually

---

packages/vendure-order-client/CHANGELOG.md
packages/vendure-order-client/package.json
packages/vendure-order-client/src/graphql-generated-types.ts
packages/vendure-order-client/src/queries.ts
packages/vendure-order-client/src/vendure-order-client.ts
packages/vendure-order-client/test/vendure-order-client.spec.ts

- Added `getActiveCustomer` and `logout()` functions;
- Removed `$currentUser` and `$eligibleShippingMethods` stores for simplicity. You should manually fetch that data in your project where needed.
`$currentUser` store was removed because it doesn't change based on actions executed, except login/logout, so it's overkill to make this a store. (My bad, I though this would come in handy).
`$eligibleShippingMethods` store was removed, because it's mostly only used in checkouts, and there you can just fetch the eligible shippingmethods when needed instead of on every cart change.
📌 Always:

feat(vendure-order-client): login and active customer

---

packages/util/src/order-state-util.ts
packages/vendure-plugin-goedgepickt/CHANGELOG.md
packages/vendure-plugin-goedgepickt/package.json
packages/vendure-plugin-sendcloud/CHANGELOG.md
packages/vendure-plugin-sendcloud/package.json
packages/vendure-plugin-sendcloud/src/api/sendcloud.service.ts
packages/vendure-plugin-sendcloud/test/sendcloud.spec.ts

Closes #312 
* Orders weren't being transitioned to Delivered after they had been shipped, because of a false type assertions.
See issue #312 for more details
📌 Always:

feat(sendcloud): fix transitioning to delivered

---

packages/vendure-plugin-selectable-gifts/CHANGELOG.md
packages/vendure-plugin-selectable-gifts/package.json
packages/vendure-plugin-selectable-gifts/src/api/gift.service.ts

* v1.1.0 is throwing an error on MySQL: 
```
"ER_WRONG_FIELD_WITH_GROUP: Expression #15 of SELECT list is not in GROUP BY clause and contains
nonaggregated column 'wkw-prod.productVariantPrices.createdAt' which is not functionally dependent 
on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"
```
* Consumers can use a custom [StockAllocationStrategy](https://docs.vendure.io/reference/typescript-api/orders/stock-allocation-strategy/), and by fetching directly from the DB, this strategy isn't used. This makes the plugin less usable for customers that use a custom strategy. The plugin now uses the variant service again. (a little less performant, but better supported)
📌 Always:

fix(selectable-gifts): mysql bugfix

---

packages/vendure-plugin-modify-customer-orders/CHANGELOG.md
packages/vendure-plugin-modify-customer-orders/package.json
packages/vendure-plugin-modify-customer-orders/src/api/order-transition-listener.service.ts
packages/vendure-plugin-modify-customer-orders/test/modify-customer-orders.spec.ts

* Always catch any promise errors in listeneres to prevent server crashes.
* Deactivate instead of delete in case of already present active order
📌 Always:

feat(modify-customer-orders): dont crash server

---

packages/vendure-plugin-popularity-scores/CHANGELOG.md
packages/vendure-plugin-popularity-scores/package.json
packages/vendure-plugin-popularity-scores/src/index.ts
packages/vendure-plugin-popularity-scores/src/popularity-scores.plugin.ts
packages/vendure-plugin-popularity-scores/src/popularity-scores.service.ts
packages/vendure-plugin-popularity-scores/src/popularity.controller.ts
packages/vendure-plugin-popularity-scores/src/utils.ts
packages/vendure-plugin-popularity-scores/test/e2e.spec.ts

The modifications in this PR involve aggregating the child `Product`s of a `Collection` in chunks when calculating it's `popularityScore`. This adjustment aims to address [this reported issue](https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/303). Closes #303 
Does this PR include any breaking changes we should be aware of?
📌 Always:

Popularity Scores Calculation Fix

---

packages/vendure-plugin-google-cloud-tasks/CHANGELOG.md
packages/vendure-plugin-google-cloud-tasks/package.json
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-controller.ts
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-job-queue.strategy.ts
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-service.ts
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.handler.ts
packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks.plugin.ts
packages/vendure-plugin-google-cloud-tasks/src/constants.ts

Sometimes job.data is too large to save in MySQL's text column, this fails job record savind, which in turn failed job processing.
* This PR retries saving without job.data when that happens
* This PR makes the plugin remove jobs older than 30 days on application startup
Needs to be deployed for Cantastic and WKW
📌 Always:

Google-cloud-tasks v1.5.0 : Prevent data too large error

---

packages/vendure-plugin-invoices/CHANGELOG.md
packages/vendure-plugin-invoices/package.json
packages/vendure-plugin-invoices/src/api/invoice-common.resolver.ts
packages/vendure-plugin-invoices/src/services/invoice.service.ts
packages/vendure-plugin-invoices/test/e2e.spec.ts

- Sort by latest invoices first in admin UI
- Don't throw error for orders without customer, because the order can be in an active state
📌 Always:

Fix(Invoices): Dont throw error for active orders and sort DESC

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts

We've changed the front-end check-out to make filling out the shipping address the default instead of making the billing address the default. It occurred to us that the shipping address is always filled in the billing address. Which doesn't make sense for us (anymore). From a Picqer API perspective the invoiceaddress is not required. So I think it's better to remove the fallback.
https://picqer.com/en/api/orders

fix: remove fallback shipping address for billing address

---

packages/vendure-plugin-goedgepickt/CHANGELOG.md
packages/vendure-plugin-goedgepickt/package.json
packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts
packages/vendure-plugin-goedgepickt/src/goedgepickt.plugin.ts
packages/vendure-plugin-goedgepickt/test/dev-server.ts

Sometimes the stock level of a variant isn't updated, because the ID of a deleted variant was fetched from the DB. This could be the case when a variant was recreated with the same SKU.
Closes #408 - This is not the approach described in the issue, but a smaller, less intrusive fix, that should still be enough for the issue at hand.
📌 Always:

Fix: Goedgepickt stock sync - ignore deleted variants

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/README.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/picqer.plugin.ts
packages/vendure-plugin-picqer/test/dev-server.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

The Picqer plugin now requires manual installation of the default order process with `checkFulfillment: false` to prevent overriding other custom order processes in the consuming projects.
Yes, the consumer must now configure the order process in vendure-config.ts
📌 Always:

feat(picqer): no more order process override

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-accept-blue/src/api/api-extensions.ts

Return `orderLine.acceptBlueSubscription.id` for subscriptions that have been created in Accept Blue
📌 Always:

feat(accept-blue): return created subscription id

---

packages/vendure-plugin-invoices/CHANGELOG.md
packages/vendure-plugin-invoices/package.json
packages/vendure-plugin-invoices/src/api/invoice-admin.resolver.ts
packages/vendure-plugin-invoices/src/services/invoice.service.ts
packages/vendure-plugin-shipmate/CHANGELOG.md
packages/vendure-plugin-shipmate/package.json
packages/vendure-plugin-shipmate/src/api/shipmate.service.ts

- Invoices: Don't throw errors when a cancelled invoice doesn't have a previous invoice, but log and return instead.
- Shipmate: Don't throw errors when an order doesn't exist, but log and return. This can happen because shipments are also manually created in Shipmate.
📌 Always:

Fix: Invoices and Shipmate - don't throw but log

---

packages/vendure-plugin-webhook/README.md

I just updated the README.md file with a working example, since the ctx is not serializable and was throwing an error before.

docs: fixed faulty example in README.md file

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/README.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-client.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-handler.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-accept-blue/test/accept-blue.spec.ts
packages/vendure-plugin-accept-blue/vitest.config.js
packages/vendure-plugin-google-storage-assets/package.json
yarn.lock

This allows you to set test mode for the accept blue plugin at the payment handler level. This is desirable in multi vendor scenario's where each vendor has an individual accept blue configuration
No, the .env variable for testMode is maintained and acts as a global override.
📌 Always:
- [ x] I have set a clear title
- [ x] My PR is small and contains a single feature
- [x ] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
- [ x] I have added or updated test cases for important functionality
- [x ] I have updated the README if needed
- [ x] I have [increased the version number](## "After increasing the version to the next patch/minor/major, the package will be published automatically after merge") in …

feat(accept-blue): allow test mode to be set at payment handler level

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/util.ts

biannually means twice a year. This means an intervalCount of 6 and an interval of 'month'. The current version treats biannually as once every 2 years.
biannually is now treated differently for subscriptions
📌 Always:
- [ x] I have set a clear title
- [ x] My PR is small and contains a single feature
- [x ] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
- [ x] I have updated the README if needed
- [ x] I have [increased the version number](## "After increasing the version to the next patch/minor/major, the package will be published automatically after merge") in `package.json`
- [ x] I have added my changes to the `CHANGELOG.md` [See this example](https://github.com/Pinelab-studio/pinelab-vendure-plugins/ …

fix(accept-blue): convert biannually to mean every 6 months

---

packages/vendure-plugin-klaviyo/CHANGELOG.md
packages/vendure-plugin-klaviyo/README.md
packages/vendure-plugin-klaviyo/package.json
packages/vendure-plugin-klaviyo/src/event-handler/klaviyo-event-handler.ts
packages/vendure-plugin-klaviyo/src/klaviyo.service.ts
packages/vendure-plugin-klaviyo/test/dev-server.ts
packages/vendure-plugin-klaviyo/test/e2e.spec.ts
packages/vendure-plugin-klaviyo/test/mock-custom-event-handler.ts
packages/vendure-plugin-klaviyo/test/mock-order-placed-handler.ts

- Allow setting multiple Klaviyo handlers for Vendure's OrderPlacedEvent
- Allow order items to be excluded from 'Ordered Product' events
📌 Always:

feat(klaviyo): Multiple order placed events and exclude items from Ordered Product events

---

packages/vendure-plugin-invoices/CHANGELOG.md
packages/vendure-plugin-invoices/package.json
packages/vendure-plugin-invoices/src/services/accounting.service.ts
packages/vendure-plugin-invoices/src/strategies/accounting/accounting-export-strategy.ts
packages/vendure-plugin-invoices/src/strategies/accounting/xero-uk-export-strategy.ts
packages/vendure-plugin-invoices/src/ui/invoices-detail-view/invoices-detail-view.ts
packages/vendure-plugin-invoices/test/dev-server.ts
packages/vendure-plugin-invoices/test/e2e.spec.ts
packages/vendure-plugin-invoices/test/mock-accounting-strategy.ts
yarn.lock

- Exporting credit invoices via accounting strategies now have their own interface method
- Don't allow accounting export when the order totals changed, to prevent mismatch between accounting export and invoice
- Added Due Date to Xero exports, which is needed for invoice approval
📌 Always:

Invoices 4.1.1 Don't allow accounting export when the order totals changed + Xero fixes

---

package.json
packages/vendure-plugin-shipmate/CHANGELOG.md
packages/vendure-plugin-shipmate/package.json
packages/vendure-plugin-shipmate/src/api/shipmate.controller.ts
yarn.lock

The changes in this PR implement and close #509
📌 Always:

Don't throw errors

---

packages/vendure-plugin-klaviyo/README.md
packages/vendure-plugin-shipmate/CHANGELOG.md
packages/vendure-plugin-shipmate/README.md
packages/vendure-plugin-shipmate/package.json
packages/vendure-plugin-shipmate/src/api/shipmate.service.ts
packages/vendure-plugin-shipmate/src/shipmate.plugin.ts
packages/vendure-plugin-shipmate/test/dev-server.ts
packages/vendure-plugin-shipmate/test/shipmate.spec.ts
yarn.lock

The changes in this PR implement and close #498 
📌 Always:

Added shouldSendOrder to ShipmatePluginConfig

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/picqer.plugin.ts
packages/vendure-plugin-picqer/test/dev-server.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

Allow specifying additional fiels on order.products in Picqer
📌 Always:

feat(picqer): added additional order line fields

---

packages/vendure-plugin-admin-social-auth/CHANGELOG.md
packages/vendure-plugin-admin-social-auth/README.md
packages/vendure-plugin-admin-social-auth/package.json
packages/vendure-plugin-admin-social-auth/src/api/google-auth-strategy.ts
packages/vendure-plugin-admin-social-auth/src/ui/login.html
packages/vendure-plugin-admin-social-auth/test/dev-server.ts

Added privacy policu on the login screen for Google OAuth approval
📌 Always:

feat(admin-social-auth): privacy policy

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/index.ts

Fixes https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/522
AcceptBlueTransactionEvent now exported from package
None
📌 Always:
- [x ] My PR is small and contains a single feature
- [x ] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
- [x ] I have updated the README if needed
- [ x] I have [increased the version number](## "After increasing the version to the next patch/minor/major, the package will be published automatically after merge") in `package.json`
- [x ] I have added my changes to the `CHANGELOG.md` [See this example](https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/main/packages/vendure-plugin-invoices/CHANGELOG.md)

fix(accept-blue): export AcceptBlueTransactionEvent from package

---

packages/vendure-plugin-google-storage-assets/CHANGELOG.md
packages/vendure-plugin-google-storage-assets/package.json
packages/vendure-plugin-google-storage-assets/src/google-storage-strategy.ts

The Google Storage strategy checks for apiType `admin` in the request context to decide if it should serve directly from CDN or via asset server. In Vendure v3 the structure of the request context changed a bit. This PR solves that, thus making the plugin v3 compatible
Nope, both V2 and V3 are supported now.
📌 Always:

feat(google-storage-assets): admin assetserver support for vendure v3

---

packages/vendure-plugin-invoices/CHANGELOG.md
packages/vendure-plugin-invoices/package.json
packages/vendure-plugin-invoices/src/services/accounting.service.ts
packages/vendure-plugin-invoices/src/strategies/accounting/xero-uk-export-strategy.ts

- Better error message extraction from Xero API response
- Limit search term for looking up contacts in Xero by max 50 characters, to prevent Xero API errors
- Log unknown errors on invoice with timestamp when accounting export fails
📌 Always:

feat(invoices): Xero exporting fixes

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/src/picqer.plugin.ts

- make falling back to parent product featured asset configurable, so that only images of variants are synced to Picqer.
This needs to happen to deploy this feature, for example:
📌 Always:

feat(picqer): allow not falling back to product image

---

packages/vendure-plugin-klaviyo/CHANGELOG.md
packages/vendure-plugin-klaviyo/package.json
packages/vendure-plugin-klaviyo/src/event-handler/klaviyo-event-handler.ts
packages/vendure-plugin-klaviyo/src/util/map-to-klaviyo-input.ts

Klaviyo's order placed event supports a DiscountCode. This PR adds support for this.

feat: add support for discount code on Klaviyo's order placed event

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-client.ts

Accept Blue expects amounts in fractions. The plugin sends amounts in cents for subscription amounts leading to multiplication by 100 of recurring values
📌 Always:
- [ x] Set a clear title
- [ x] I have checked my own PR
- [ x] Increased the version number in `package.json`
- [ x] Added changes to the `CHANGELOG.md`

fix(accept-blue): divide recurring amounts by 100

---

packages/vendure-plugin-metrics/CHANGELOG.md
packages/vendure-plugin-metrics/package.json
packages/vendure-plugin-metrics/src/ui/chartist/chartist.component.scss

Description
- fixed the font color for metrics plugin when in dark mode

fix(metrics): font color fix for dark mode in metrics

---

packages/vendure-plugin-facet-suggestions/CHANGELOG.md
packages/vendure-plugin-facet-suggestions/package.json
packages/vendure-plugin-facet-suggestions/src/ui/suggested-facets-component/suggested-facets.component.ts

In Vendure 3.1.1 we also need `productGroup.controls.facetValueIds.markAsDirty();` next to the already existing `productGroup.markAsDirty();`
Fixes #552 
📌 Always:

feat(facet-suggestions): admin ui fix

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-transaction-event.ts
packages/vendure-plugin-accept-blue/src/api/api-extensions.ts
packages/vendure-plugin-accept-blue/src/types.ts

We want to better understand what happened if a payment doesn't go through for some reason and be able to view the history of this. Therefore, I added a logHistoryEntry for accept blue
Also, I added ctx to the event. This would allow us to capture the event and affect channel specific processing.
I didn't write tests for this (yet). Please have a look and see if you think we can proceed with this change and I can write a test
No update has been done yet to README or version
📌 Always:
- [ x] Set a clear title
- [x ] I have checked my own PR

feat(accept-blue): add ctx for event, log order history entry

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/README.md
packages/vendure-plugin-accept-blue/src/api/accept-blue-client.spec.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-client.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-common-resolvers.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-handler.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-accept-blue/src/api/api-extensions.ts
packages/vendure-plugin-accept-blue/src/types.ts
packages/vendure-plugin-accept-blue/test/accept-blue.spec.ts
packages/vendure-plugin-accept-blue/test/dev-server.ts
packages/vendure-plugin-accept-blue/test/helpers/graphql-helpers.ts
packages/vendure-plugin-accept-blue/test/helpers/mocks.ts

- Allow disabling certain payment methods, e.g. 'visa' or 'check', via the Vendure Admin UI
- Expose surcharges used by Accept Blue via GraphQL query
📌 Always:

feat(accept-blue): implementing eligible methods and surcharges

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-client.spec.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-client.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-handler.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-accept-blue/src/types.ts
packages/vendure-plugin-accept-blue/src/util.ts

- Renamed internals to Amex as well
- Not checking for `sec_code` input anymore, as it is an optional argument
📌 Always:

Accept Blue v2.4.0 - Renamed to Amex and removed `sec_code` check

---

package.json
packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/README.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-common-resolvers.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-handler.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-accept-blue/src/api/api-extensions.ts
packages/vendure-plugin-accept-blue/src/types.ts
packages/vendure-plugin-accept-blue/test/accept-blue.spec.ts
packages/vendure-plugin-accept-blue/test/helpers/graphql-helpers.ts
yarn.lock

- Expose tokenization key, and Google merchant id's on payment method quote and eligible Accept Blue methods.
📌 Always:

feat(accept-blue): expose storefront keys on payment methods

---

packages/vendure-plugin-goedgepickt/CHANGELOG.md
packages/vendure-plugin-goedgepickt/package.json
packages/vendure-plugin-goedgepickt/src/api/goedgepickt.handler.ts
packages/vendure-plugin-goedgepickt/src/api/goedgepickt.service.ts
packages/vendure-plugin-goedgepickt/test/goedgepickt.spec.ts

- Process stock updates via the job queue, so that it is retried when GoedGepickt returns a `Too Many Attempts` error
- Don't use GoedGepickt as fulfilment handler anymore, instead directly move to `Shipped` or `Delivered` on incoming status change.
📌 Always:

GoedGepickt: Skip fulfilment and retry stock updates via the Job queue

---

packages/vendure-plugin-picqer/CHANGELOG.md
packages/vendure-plugin-picqer/package.json
packages/vendure-plugin-picqer/src/api/picqer.service.ts
packages/vendure-plugin-picqer/test/picqer.spec.ts

- Hydrate `ProductVariant.Product` when pushing products to Picqer, so that consumers can use Product to populate Picqer custom fields.
-
📌 Always:

feat(picqer): hydrate variant.product relation when pushing to picqer

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-common-resolvers.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-order-pdfs/README.md

- Prevent throwing an error when no enabled Accept Blue payment method is found when fetching other eligible Payment Methods.
📌 Always:

feat(accept-blue): prevent error throwing on disabled Accept Blue method

---

packages/vendure-plugin-metrics/CHANGELOG.md
packages/vendure-plugin-metrics/package.json
packages/vendure-plugin-metrics/src/ui/metrics-ui.service.ts
packages/vendure-plugin-metrics/src/ui/metrics-widget.ts

Fixed a bug where variant IDs were not being passed correctly to the metrics query.
Also cleans up some unused variables and improves types from `any` by assigning values at declaration.
- N/A
None
📌 Always:

fix(metrics): variant IDs are not being passed to the backend query after initial load

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-service.ts
packages/vendure-plugin-accept-blue/src/api/api-extensions.ts
packages/vendure-plugin-accept-blue/test/dev-server.ts
packages/vendure-plugin-accept-blue/test/helpers/graphql-helpers.ts
packages/vendure-plugin-shipping-extensions/src/config/shipping/shipping-util.ts

- BREAKING: `AcceptBlueSubscription.recurring.endDate` is removed.
- BREAKING: `AcceptBlueSubscription.recurring.startDate` is now optional.
- The fields `createdAt`, `nextRunDate`, `previousRunDate` and `numLeft` have been added to `AcceptBlueSubscription.recurring`.
Yes, see above
📌 Always:

feat(accept-blue): Removed `endDate` and made `startDate` optional

---

packages/vendure-plugin-stripe-subscription/CHANGELOG.md
packages/vendure-plugin-stripe-subscription/package.json
packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.resolver.ts
packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.service.ts

- Removes the hard-coded array of paymentMethods and setup_future_usage: 'off_session'  from the createIntentByOrder service.
- Shifts the responsibility for defining paymentMethods and setup_future_usage: 'off_session' into the resolver.
- Allows caller (e.g. resolver, controller ) to pass an array of payment methods (e.g. ['card'], ['affirm', 'card']) and setupFurtureUsage based on order or channel to the service.
- `StripeSubscriptionService.createIntentByOrder`, `StripeSubscriptionService.createIntent`, and `StripeSubscriptionService.createIntentForDraftOrder` now requires a `paymentMethods: string[]` and  `setupFurtureUsage` argument;
- Previously, the `StripeSubscriptionService.createIntentByOrder` method had a hardcoded `const paymentMethods = ['card']`, making the service …

feat(stripe-subscription): move default stripePaymentMethods from service to resolver

---

packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/README.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/api/accept-blue-admin-resolver.ts
packages/vendure-plugin-accept-blue/src/api/accept-blue-common-resolvers.ts
packages/vendure-plugin-accept-blue/src/api/api-extensions.ts
packages/vendure-plugin-accept-blue/src/service/accept-blue-service.ts
packages/vendure-plugin-accept-blue/test/accept-blue.spec.ts
packages/vendure-plugin-accept-blue/test/dev-server.ts
packages/vendure-plugin-accept-blue/test/helpers/graphql-helpers.ts
packages/vendure-plugin-accept-blue/test/helpers/mocks.ts

- Enable updating payment method on a subscription via the Shop API for logged in customers
- Bug fix: Prevent updating a subscription to a payment method type (Visa, MasterCard, etc) that is not allowed. Only allow the methods set via the Admin UI.
📌 Always:

Accept Blue: Allow updating payment method by customers

---

packages/vendure-plugin-stripe-subscription/CHANGELOG.md
packages/vendure-plugin-stripe-subscription/package.json
packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.service.ts

- Skip intent processing in handleIntentSucceeded if the order is already in PaymentSettled state
None
- There was no check before creating the stripe subscription to see if the order was already settled. sometimes the order is already settled, but the API responds with an error. Stripe retries the request and ends up creating another subscription. after that, when the code tries to settle the payment (which is already done), it throws an error. This check should have happened before creating the subscription to avoid these issues.
📌 Always:

Fix duplicate Stripe subscription on webhook retries

---

packages/util/src/subscription/subscription-helper.ts
packages/vendure-plugin-accept-blue/CHANGELOG.md
packages/vendure-plugin-accept-blue/package.json
packages/vendure-plugin-accept-blue/src/accept-blue-plugin.ts
packages/vendure-plugin-accept-blue/src/service/accept-blue-client.ts
packages/vendure-plugin-accept-blue/src/service/accept-blue-service.ts
packages/vendure-plugin-accept-blue/src/service/subscription-order-item-calculation.ts
packages/vendure-plugin-accept-blue/test/accept-blue.spec.ts
packages/vendure-plugin-accept-blue/test/helpers/test-subscription-strategy.ts
packages/vendure-plugin-stripe-subscription/CHANGELOG.md
packages/vendure-plugin-stripe-subscription/package.json

- Breaking: `amountDueNow` was not actually being used to calculate the line price! If you used `variant.price` in your subscription strategy, or used the default subscription strategy, everything still works as expected.
- Allow subscriptions with `amount=0`
- Delete created subscriptions if the one-time charge fails after that.
📌 Always:

feat(accept-blue): using amount due now, and delete created subscriptions on failure
